services:
- type: web
  name: GPT-Memory-Project
  runtime: python
  repo: https://github.com/10John01/GPT-Memory-Project
  branch: main
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn chat_memory_system:app --bind 0.0.0.0:$PORT
