services:
  - type: web
    name: GPT-Memory-System
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chat_memory_system:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SUPABASE_URL
        value: https://mhlkzlxbeslcdvpkhfrr.supabase.co
      - key: SUPABASE_KEY
        value: your_supabase_key
      - key: SUPABASE_SERVICE_ROLE
        value: your_service_role_key
      - key: PORT
        value: 22531
